swagger: "2.0"
info:
  title: PM Subscription Handler Service
  version: "1.0.0"
  description: This is the swagger file that outlines the PM subscription handler api
consumes:
  - "application/json"
produces:
  - "application/json"

# Paths supported by the server application
paths:
  /healthcheck:
    get:
      operationId: "mod.healthcheck.status"
      tags:
        - "HealthCheck"
      description: >-
        This is the health check endpoint. If this returns a 200, the server is alive.
      responses:
        200:
          description: Successful response
          schema:
            type: object
            properties:
              status:
                type: string
                description: Overall health of PMSH
                enum: [healthy, unhealthy]
        '503':
          description: the pmsh service is unavailable
