#    ============LICENSE_START=======================================================
#    ml-prediction-ms
#    ================================================================================
#     Copyright (C) 2020 Wipro Limited.
#     ==============================================================================
#       Licensed under the Apache License, Version 2.0 (the "License");
#       you may not use this file except in compliance with the License.
#       You may obtain a copy of the License at
#
#            http://www.apache.org/licenses/LICENSE-2.0
#
#       Unless required by applicable law or agreed to in writing, software
#       distributed under the License is distributed on an "AS IS" BASIS,
#       WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#       See the License for the specific language governing permissions and
#       limitations under the License.
#     ============LICENSE_END=========================================================

version: '2.4'
networks:
  ml-prediction-ms-default:
    driver: bridge
    driver_opts:
      com.docker.network.driver.mtu: 1400
services: 
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
    networks:
      - ml-prediction-ms-default
  kafka:
    image: wurstmeister/kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: "kafka"
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'true'
      KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181"
      KAFKA_ADVERTISED_LISTENERS: "PLAINTEXT://kafka:9092"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - zookeeper
    networks:
      - ml-prediction-ms-default
  dmaap:
    image: nexus3.onap.org:10001/onap/dmaap/dmaap-mr:1.1.8  
    ports:
      - "3904:3904"
      - "3905:3905"
    volumes:
      - ./config/dmaap/MsgRtrApi.properties:/appl/dmaapMR1/bundleconfig/etc/appprops/MsgRtrApi.properties
    depends_on:
      - zookeeper
      - kafka
    networks:
      - ml-prediction-ms-default
  ml-prediction-ms:
    container_name: ml-prediction-ms
    build:
      context: ../ml-prediction-ms
    ports:
      - "5000:5000"
    environment:
      - DEBUG=True
    depends_on:
      - dmaap
      - zookeeper
      - kafka
    networks:
      - ml-prediction-ms-default 
